[colors.bright]
black = "0x575b70"
blue = "0xcaa9fa"
cyan = "0x9aedfe"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xf4f99d"

[colors.normal]
black = "0x000000"
blue = "0xcaa9fa"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[font]
size = 14.0

[font.bold]
family = "PT Mono"

[font.bold_italic]
family = "PT Mono"

[font.italic]
family = "PT Mono"

[font.normal]
family = "PT Mono"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[selection]
save_to_clipboard = true

[window]
option_as_alt = "Both"

[window.dimensions]
columns = 125
lines = 35

[window.padding]
x = 8
y = 3
