# General
alias confluence='~/lib/confluence.sh';
alias ctags='~/lib/ctags.sh';
alias edit='$EDITOR';
alias gg='git grep';
alias github='~/lib/github.sh';
alias goal='DATABASE_NAME="GOALS" list-cli';
alias htop='~/lib/htop.sh';
alias icebox='DATABASE_NAME="ICEBOX" list-cli';
alias jira='~/lib/jira.sh';
alias l='~/lib/ls.sh -CF';
alias la='~/lib/ls.sh -la';
alias list='list-cli';
alias ll='~/lib/ls.sh -l';
alias ls='~/lib/ls.sh';
alias mysql='~/lib/mysql.sh';
alias note='DATABASE_NAME="NOTES" list-cli';
alias psql='~/lib/psql.sh';
alias pypi='~/lib/pypi.sh';
alias question='DATABASE_NAME="QUESTIONS" list-cli';
alias readlink='~/lib/readlink.sh';
alias rubygems='~/lib/rubygems.sh';
alias screen='~/lib/screen.sh';
alias sed='~/lib/sed.sh';
alias setenv='source ~/lib/setenv.sh';
alias tmux='~/lib/tmux.sh';
alias todo='DATABASE_NAME="TODO" list-cli';
alias vi='vim';
alias vim='~/lib/vim.sh';

# The ability to navigate 10 directories up should be enough to cover most cases
alias ..='cd ..';
alias ...='cd ../..';
alias ....='cd ../../..';
alias .....='cd ../../../..';
alias ......='cd ../../../../..';
alias .......='cd ../../../../../..';
alias ........='cd ../../../../../../..';
alias .........='cd ../../../../../../../..';
alias ..........='cd ../../../../../../../../..';
alias ...........='cd ../../../../../../../../../..';
